version: '3.7'

services:
  smokey:
    image: ghcr.io/kittensaredabest/smokey:latest
    restart: always
    hostname: smokey
    ports:
      - 3000:3000
    volumes:
      - ./config.json:/app/public/config.json